namespace CFramework.Editor.UISystem
{
    public static class Templates
    {
        public const string UILayerTemplate = @"// Auto-generated by CFramework UI LayerGenerator
namespace {{Namespace}}
{
    public static class {{ClassName}}
    {
{{#each Layers}}
        public const string {{this.Name}} = ""{{this.Value}}"";
{{/each}}    }
}";

        public const string UITransitionTemplate = @"// Auto-generated by CFramework UI TransitionGenerator
namespace {{Namespace}}
{
    public static class {{ClassName}}
    {
{{#each Transitions}}
        public const string {{this.Name}} = ""{{this.Value}}"";
{{/each}}    }
}";
    }
}