namespace CFramework.Editor.AddressablesTools
{
    public static class Templates
    {
        public const string TemplateSingleClass = @"// Auto-generated by CFramework AddressablesCodeGen
namespace {{Namespace}}
{
    public static class {{ClassName}}
    {
{{#each Groups}}
{{#each this.Entries}}
        public const string {{this.Identifier}} = ""{{this.Address}}"";
{{/each}}
{{/each}}
    }
}";

        public const string TemplateNestedByGroup = @"// Auto-generated by CFramework AddressablesCodeGen
namespace {{Namespace}}
{
    public static class {{ClassName}}
    {
{{#each Groups}}
        public static class {{this.GroupClassName}}
        {
{{#each this.Entries}}
            public const string {{this.Identifier}} = ""{{this.Address}}"";
{{/each}}        }
{{/each}}
    }
}";

        public const string TemplateSplitByGroupMain = @"// Auto-generated by CFramework AddressablesCodeGen
namespace {{Namespace}}
{
    public static class {{ClassName}}
    {
    }
}";

        public const string TemplateSplitByGroup = @"// Auto-generated by CFramework AddressablesCodeGen
namespace {{Namespace}}
{
    public static class {{ClassName}}_{{GroupClassName}}
    {
{{#each Entries}}
        public const string {{this.Identifier}} = ""{{this.Address}}"";
{{/each}}    }
}";

        public const string TemplatePartialCombined = @"// Auto-generated by CFramework AddressablesCodeGen
namespace {{Namespace}}
{
    public static partial class {{ClassName}}
    {
        public static class {{GroupClassName}}
        {
{{#each Entries}}
            public const string {{this.Identifier}} = ""{{this.Address}}"";
{{/each}}        }
    }
}";

        public const string TemplateLabels = @"// Auto-generated by CFramework AddressablesCodeGen
namespace {{Namespace}}
{
    public static class {{ClassName}}
    {
{{#each Labels}}
        public const string {{this.Identifier}} = ""{{this.Label}}"";
{{/each}}    }
}";
    }
}